(require :sdl2)

(defun clear (renderer &key (color '(105 105 105 255)))
  (apply #'sdl2:set-render-draw-color renderer color)
  (sdl2:render-clear renderer))

(defun rect (renderer x y w h &key (color '(255 140 0 255)))
  (apply #'sdl2:set-render-draw-color renderer color)
  (sdl2:render-fill-rect renderer (sdl2:make-rect x y w h)))

(defun ui ()
  (sdl2:with-init (:everything)
    (sdl2:with-window (win :title "UI Test" :flags '(:shown))
      (sdl2:with-renderer (renderer win :flags '(:accelerated))
        (sdl2:with-event-loop (:method :poll)
          (:keyup (:keysym keysym)
            (case (sdl2:scancode keysym)
              (:scancode-escape (sdl2:push-event :quit))))
          (:idle ()
            (clear renderer)
            (rect renderer 0 0 200 200)
            (sdl2:render-present renderer)
	        (sdl2:delay 33))
          (:quit () t))))))
